# Generated by Django 6.0.7 on 2026-08-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
