# Generated by Django 6.0.7 on 2026-08-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_userprofile_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gamer_tag",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
