# Generated by Django 6.0.7 on 2026-08-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="developer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="publisher",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
