# Generated by Django 6.0.7 on 2026-08-17 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("source_name", models.CharField(blank=True, max_length=150)),
                ("source_url", models.URLField(blank=True)),
                ("author", models.CharField(blank=True, max_length=150)),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                ("published_at", models.DateTimeField()),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="games.game",
                    ),
                ),
            ],
        ),
    ]
