# Generated by Django 6.0.7 on 2026-08-01 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_screenshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="screenshot",
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.CreateModel(
            name="DLC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EXPANSION", "Expansion"),
                            ("SEASON_PASS", "Season Pass"),
                            ("COSMETIC", "Cosmetic"),
                            ("CONTENT_PACK", "Content Pack"),
                        ],
                        default="EXPANSION",
                        max_length=30,
                    ),
                ),
                ("cover", models.ImageField(upload_to="games/dlcs/")),
                ("release_date", models.DateField()),
                ("purchase_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dlcs",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
