# Generated by Django 6.0.7 on 2026-08-01 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_screenshot_options_dlc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("IGN", "IGN"),
                            ("FEXTRALIFE", "Fextralife"),
                            ("STEAM", "Steam Community"),
                            ("YOUTUBE", "YouTube"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guides",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
